name: douyin
description: douyin

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # 屏幕适配
  flutter_screenutil: ^3.2.0
  # 持久化数据
  shared_preferences: ^0.5.12+2
  # 全局数据
  scoped_model: ^1.1.0
  # 生成二维码
  qr_flutter: ^3.2.0
  # 权限申请
  permission_handler: ^5.0.1+1
  # 事件插件
  event_bus:  ^1.1.1
  # 打开外部浏览器
  url_launcher: ^5.7.8
  # 保存图片
  image_gallery_saver : ^1.6.1
  # # 上传组件
  # # flutter_uploader : ^1.2.0
  # 获取路径
  path_provider : ^1.6.22
  # 相册选择器
  image_picker: ^0.6.7+12
  # 设备信息
  device_info : ^0.4.2+9
  # md5
  crypto: ^2.1.5

  # 视频插件
  video_player:
    path: ./packages/video_player-1.0.0

  # AES加密
  steel_crypt:
    path: ./packages/steel_crypt-2.2.2+1
  # AES加密
  flutter_aes:
    path: ./packages/flutter_aes-0.1.1
  # 刷新插件
  flutter_easyrefresh:
    path: ./packages/flutter_easyrefresh-2.1.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  connectivity: 2.0.0
  dio: ^3.0.10


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - locale/i18n_en.json
    - locale/i18n_zh.json
    - images/common_btn_bg.png
    - images/icon_circular_blue.png
    - images/icon_circular_red.png
    - images/icon_circular.png
    - images/icon_hot.png
    - images/icon_main.png
    - images/icon_me.png
    - images/icon_message.png
    - images/icon_sex_boy.png
    - images/icon_sex_girl.png

    - images/mine/agent_topbg.png
    - images/mine/icon_gotomsg.png
    - images/mine/icon_gotoplay.png
    - images/mine/icon_play.png
    - images/mine/icon_service.png
    - images/mine/info_bg_level.png
    - images/mine/info_icon_local.png
    - images/mine/option_share.png
    - images/mine/option_upload.png
    - images/mine/option_vip.png
    - images/mine/video_top.png
    - images/mine/pay/choosebtn_00.png
    - images/mine/pay/choosebtn_01.png
    - images/mine/pay/coin_book.png
    - images/mine/pay/coin_coin.png
    - images/mine/pay/coin_package.png
    - images/mine/pay/payway_alipay.png
    - images/mine/pay/payway_wechat.png
    - images/mine/pay/vip_level_1.png
    - images/mine/pay/vip_level_2.png
    - images/mine/pay/vip_level_3.png

    - images/replace/head.jpg
    - images/replace/hot_bg.png
    - images/replace/invite_bg.jpg
    - images/replace/logo.png
    - images/replace/share_videobg.jpg
    - images/replace/start.jpg
    - images/replace/videocover.jpg

    - images/video/bottom_compilation.png
    - images/video/bottom_hot.png
    - images/video/btn_goto_00.png
    - images/video/btn_goto_01.png
    - images/video/btn_gotouser.png
    - images/video/gift_1.png
    - images/video/gift_2.png
    - images/video/gift_3.png
    - images/video/gift_4.png
    - images/video/icon_getall.png
    - images/video/icon_maillist.jpg
    - images/video/icon_donotdisturb.png
    - images/video/icon_follow_00.png
    - images/video/icon_follow_01.png
    - images/video/icon_online.png
    - images/video/icon_onlive.png
    - images/video/icon_play.png
    - images/video/mark_icon_fire.png
    - images/video/mark_icon_rank.png
    - images/video/right_comment.png
    - images/video/right_gift_00.png
    - images/video/right_gift_01.png
    - images/video/right_gift_02.png
    - images/video/right_gift_03.png
    - images/video/right_gift_04.png
    - images/video/right_gift_05.png
    - images/video/right_gift_06.png
    - images/video/right_gift.png
    - images/video/right_like_00.png
    - images/video/right_like_01.png
    - images/video/right_share.png
    - images/video/share_btnbg.png
    - images/video/text_hot.png
    - images/video/top_search.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
